# Scipy：高级科学计算

+ scipy包包含许多专注于科学计算中的常见问题的工具箱。它的子模块对应于不同的应用，比如插值、积分、优化、图像处理、统计和特殊功能等。
+ scipy可以与其他标准科学计算包相对比，比如Matlab的工具箱。scipy是Python中科学程序的核心程序包；这意味着有效的操作numpy数组，因此，numpy和scipy可以一起工作。
+ 在实现一个程序前，有必要确认一下需要的数据处理时候已经在scipy中实现。

| 子模块 | 用途 |
| ----- | ---- |
|scipy.cluster	|向量计算 / Kmeans|
|scipy.constants|物理和数学常量|
|scipy.fftpack	|傅里叶变换|
|scipy.integrate	|积分程序|
|scipy.interpolate	|插值|
|scipy.io	|数据输入和输出|
|scipy.linalg	|线性代数程序|
|scipy.ndimage	|n-维图像包|
|scipy.odr	|正交距离回归|
|scipy.optimize	|优化|
|scipy.signal	|信号处理|
|scipy.sparse	|稀疏矩阵|
|scipy.spatial	|空间数据结构和算法|
|scipy.special	|一些特殊数学函数|
|scipy.stats	|统计|


## 1.1 导入方式
他们全都依赖于numpy, 但是大多数是彼此独立的。导入Numpy和Scipy的标准方式：

In [1]:
import numpy as np
from scipy import stats  # 其他的子模块类似

## 1.2 文件的输入与输出

In [2]:
from scipy import io as spio
a = np.ones((3, 3))
spio.savemat('file.mat', {'a': a}) # savemat expects a dictionary
data = spio.loadmat('file.mat', struct_as_record=True)
data['a']

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

## 1.3 特殊函数 scipy.special
scipy.special模块的文档字符串写的很详细，因此我们不会在这里列出所有的函数。常用的一些函数如下：
+ 贝塞尔函数，比如scipy.special.jn() (第n个整型顺序的贝塞尔函数)
+ 椭圆函数 (scipy.special.ellipj() Jacobian椭圆函数, ...)
+ Gamma 函数: scipy.special.gamma(), 也要注意 scipy.special.gammaln() 将给出更高准确数值的 Gamma的log。
+ Erf, 高斯曲线的面积：scipy.special.erf()

## 1.4 线性代数操作 scipy.linalg
scipy.linalg 模块提供了标准的线性代数操作
+ scipy.linalg.det() 函数计算方阵的行列式：

In [3]:
from scipy import linalg
arr = np.array([[1, 2],
                [3, 4]])
linalg.det(arr)

-2.0

In [4]:
arr = np.array([[3, 2],
                 [6, 4]])
linalg.det(arr)

6.661338147750939e-16

In [5]:
linalg.det(np.ones((3, 4)))

ValueError: expected square matrix

+ scipy.linalg.inv() 函数计算逆方阵：

In [7]:
arr = np.array([[1, 2],
                 [3, 4]])
iarr = linalg.inv(arr)
iarr

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [8]:
np.allclose(np.dot(arr, iarr), np.eye(2))

True

最后计算逆奇异矩阵（行列式为0）将抛出LinAlgError :

In [9]:
arr = np.array([[3, 2],
                 [6, 4]])
linalg.inv(arr)

LinAlgError: singular matrix

+ 还有更多高级的操作，奇异值分解（SVD）：

In [11]:
arr = np.arange(9).reshape((3, 3)) + np.diag([1, 0, 1])
uarr, spec, vharr = linalg.svd(arr)
spec

array([ 14.88982544,   0.45294236,   0.29654967])

In [12]:
sarr = np.diag(spec)
svd_mat = uarr.dot(sarr).dot(vharr)
np.allclose(svd_mat, arr)

True

SVD常被用于统计和信号处理。其他标准分解 (QR, LU, Cholesky, Schur), 以及线性系统的求解器，也可以在scipy.linalg中找到。