## 1、导入numpy库并简写为 np

In [1]:
import numpy as np

## 2、创建数组
+ （1）创建从0到9的一维数组
+ （2）创建一个长度为10的空向量
+ （3）确定两个数组的内存大小
+ （4）创建一个 3x3 的单位矩阵
+ （5）创建一个 3x3的随机数组，并找到它的最大值和最小值

In [66]:
array = np.arange(10)
print("%d bytes" % (array.size * array.itemsize))
array

40 bytes


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
array = np.zeros(10)
print("%d bytes" % (array.size * array.itemsize))
array

80 bytes


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [68]:
array = np.eye(3)
array

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [71]:
array = np.random.random((3, 3))
print ('the maximum is ', array.max())
print ('the minimum is ', array.min())
array

the maximum is  0.937571583951
the minimum is  0.108193382887


array([[ 0.60074272,  0.16797218,  0.73338017],
       [ 0.40844386,  0.52790882,  0.93757158],
       [ 0.52169612,  0.10819338,  0.15822341]])

## 3、创建一个3*3的二维数组，值全为True

In [6]:
array = np.full((3,3),True)
array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

## 4、创建一个3×3的数组，值域为0到8。
+ （1）按行反转这个数组
+ （2）按列反转这个数组
+ （3）求每行的最大值

In [49]:
array = np.arange(9).reshape(3,3)
max_num = np.max(array,axis=0)
print ('the max value in each row', max_num)
print('the original matrix is \n', array)
array = array[::-1,:]
print('the matrix converted by row is \n', array)
array = array[:,::-1]
print('the matrix converted by column is \n', array)

the max value in each row [6 7 8]
the original matrix is 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
the matrix converted by row is 
 [[6 7 8]
 [3 4 5]
 [0 1 2]]
the matrix converted by column is 
 [[8 7 6]
 [5 4 3]
 [2 1 0]]


## 5、从数组np.array([1, 2, 0, 0, 4, 0])中找出非0元素的位置索引，并检测数组中有无NaN值

In [56]:
array = np.array([1, 2, 0, 0, 4, 0])
index = np.where(array!=0)
print('the index is ', index)
is_na = np.isnan(array).any()
is_na

the index is  (array([0, 1, 4], dtype=int64),)


False

## 6、从数组np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])中提取所有的奇数, 并在不改变原数组的条件下，将所有数组的奇数位置全部替换成-1.

In [41]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_nums = array[array%2!=0]
print ('the odd number in array is \n', odd_nums)
arr = np.where(array%2!=0,-1,array)
print ('replace the odd number by -1 \n', arr)

the odd number in array is 
 [1 3 5 7 9]
replace the odd number by -1 
 [ 0 -1  2 -1  4 -1  6 -1  8 -1]


## 7、将一维数组np.arange(10)转换为2行的二维数组

In [12]:
array = np.arange(10).reshape((2,-1))
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 8、有数组a = np.arange(10).reshape(2,-1)和数组b = np.repeat(1, 10).reshape(2,-1)
+ （1）将数组a和b进行垂直堆叠
+ （2）将数组a和b进行水平堆叠

In [27]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print('a is \n',a)
print('b is \n',b)
array=np.vstack((a,b))
print('the matrix after vertical stack is \n', array)
array = np.hstack((a,b))
print('the matrix after horizontal stack is \n', array)

a is 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
b is 
 [[1 1 1 1 1]
 [1 1 1 1 1]]
the matrix after vertical stack is 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
the matrix after horizontal stack is 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## 9、有数组a = np.array([1,2,3,2,3,4,3,4,5,6])和数组b = np.array([7,2,10,2,7,4,9,4,9,8])
+ （1）获取数组元素相匹配的位置
+ （2）获取数组a,b相同的元素
+ （3）从数组a中删除在数组b中存在的所有元素
+ （4）删除数组a中的重复值，并统计各元素数量
+ （5）计算两数组的欧氏距离

In [51]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
location = np.where(a==b)
print('the location is \n',location)
elements = np.intersect1d(a,b)
print('the same elements is \n', elements)
index = np.array([item in b for item in a])
array = a[~index]
print('the changed a is \n', array)
count = np.unique(a,return_counts=True)
print('the unique value is \n', count)
distance = np.sqrt(np.sum((a-b)**2))
print('the distance is \n', distance)

the location is 
 (array([1, 3, 5, 7], dtype=int64),)
the same elements is 
 [2 4]
the changed a is 
 [1 3 3 3 5 6]
the unique value is 
 (array([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 2, 1, 1], dtype=int64))
the distance is 
 12.5299640861


## 10、创建0到14的一维数组
+ （1）从数组中提取5到10之间的所有数字
+ （2）在随机位换成值44

In [23]:
array = np.arange(15)
index = np.where((array>=5) & (array<=10))
nums = array[index]
nums

array([ 5,  6,  7,  8,  9, 10])

In [42]:
np.random.seed(100)
array[np.random.choice(len(array))] = 44
array

array([ 0,  1,  2,  3,  4,  5,  6,  7, 44,  9])

## 11、先交换数组np.arange(9).reshape(3,3)中的第1列和第2列，在此基础之上交换数组的第1行和第2行

In [28]:
array = np.arange(9).reshape(3,3)
print('the original matrix is \n', array)
array = array[:,[1,0,2]]
print('the changed matrix is \n',array)
array = array[[1,0,2],:]
print('the changed matrix is \n',array)

the original matrix is 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
the changed matrix is 
 [[1 0 2]
 [4 3 5]
 [7 6 8]]
the changed matrix is 
 [[4 3 5]
 [1 0 2]
 [7 6 8]]


## 12、如何创建一个形状为5x3的二维数组，其包含5到10之间的随机浮点数

In [29]:
array = np.random.rand(5,3)+np.random.randint(low=5,high=10,size=(5,3))
array

array([[ 5.2407627 ,  6.37447771,  6.49730178],
       [ 7.44885241,  5.60905416,  8.25700536],
       [ 6.06438774,  6.95553597,  5.84416985],
       [ 5.41299461,  5.40984907,  7.41576226],
       [ 8.38411229,  8.6819244 ,  7.44855007]])

## 13、起点2，长度10，步长3，创建一个numpy数组

In [52]:
array = np.arange(2,3*10+2,3)
array

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

## 14、从二维数组a = np.array([[3,3,3],[4,4,4],[5,5,5]])中的每行减去一维数组b = np.array([1,2,3])中相应的值

In [54]:
a = np.array([[3,3,3],[4,4,4],[5,5,5]])
b = np.array([1,2,3])
array = a-b[:,np.newaxis]
array

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

## 15、生成一个含nan的一维数组，并将nan替换为0

In [58]:
array = np.array([1,2,3,2,np.nan,4,3,4,5,6])
array[np.isnan(array)] = 0
array

array([ 1.,  2.,  3.,  2.,  0.,  4.,  3.,  4.,  5.,  6.])

## 16、把数组np.random.randint(1,10(3,3))按照数组最后一列的数值进行排序

In [60]:
np.random.seed(4)
array = np.random.randint(1,10,(3,3))
order = np.argsort(array[:,-1])
array = array[order,:]
array

array([[8, 6, 2],
       [3, 8, 8],
       [9, 8, 9]])

## 17、有数组np.array([7,2,10,2,7,4,9,4,9,8])
+ （1）数组第二大值
+ （2）求出现频率最高的值

In [62]:
array = np.array([7,2,10,2,7,2,4,9,4,9,8])
num = np.unique(array)[-2]
most_frequent = np.unique(array,return_counts=True)[0][0]
print('the second biggest value is ',num)
print('the most frequent value is ',most_frequent)

the second biggest value is  9
the most frequent value is  2


## 18、创建一个5*5的矩阵，每行的数值都是从0到4

In [63]:
array1 = np.arange(5)
array2 = np.zeros((5,5))
array = array1+array2
array

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

## 19、对于一个数组，如何添加一个用0填充的边界?  
这个在机器学习的卷积网络中是很重要的

In [73]:
a = np.ones((5, 5))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
a

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])